apiVersion: v1
kind: ServiceAccount
metadata:
    name: test2-sa
    namespace: test2
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: test2-tiller
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
subjects:
    - kind: ServiceAccount
      name: test2-sa
      namespace: test2
